### PR TITLE
Format docs.md

### PR DESCRIPTION
**Pull request by jackwener**
### What problem does this PR solve?

Issue Number: #7438

### What is changed and how it works?

What's Changed:

Format docs.md

### Related changes

None

Side effects

- None

RELEASE NOTES: 

None

### CODE REVIEW

**Comment by jackwener** [comment]
@Aries-Lee1991 PTAL

**Review by Aries-Lee1991 — CHANGES_REQUESTED** [review]
Thank you for your contribution. Can you correct the sentence in the table?

**Comment by jackwener** [comment]
> Thank you for your contribution. Can you correct the sentence in the table?

I have finish correct it.

**Review by Aries-Lee1991 — APPROVED** [review]
LGTM

**Comment by Aries-Lee1991** [comment]
Here is my WeChat: Aries_Lee1991. Looking forward to your joining our contributor group. @jackwener

**Comment by Eliacy** [comment]
LGTM

**Comment by Aries-Lee1991** [comment]
@jackwener #7476 is submitted to the master branch, but the default branch of TDengine project is develop. Your name will appear in the contributor list only when you submit to the develop branch. Therefore, please resubmit to the develop branch. Thank you.

**Pull request merged**
