### PR TITLE
[TD-13785]<fix>: change method for jdbc judge update or query

### PR DESCRIPTION
**Pull request by huolibo**

### CODE REVIEW

**Review by dingbo8128 — COMMENTED** [review]
Why not use the same way as JNI ?

**Comment by huolibo** [comment]
> Why not use the same way as JNI ?

because  restful API can not call method in taos.lib

**Review by dingbo8128 — APPROVED** [review]
LGTM

**Review by zyyang-taosdata — APPROVED** [review]
LGTM

**Pull request merged**
