### PR TITLE
fix(driver): delete java connector in TDengine

### PR DESCRIPTION
**Pull request by huolibo**

### CODE REVIEW

**Comment by sangshuduo** [comment]
Need to modify CMakeLists.txt to make the build pass first.

**Review by sangshuduo — CHANGES_REQUESTED** [review]
Need to modify CMakeLists.txt to make the build pass first.

**Review by dingbo8128 — APPROVED** [review]
LGTM

**Review by sangshuduo — APPROVED** [review]
LGTM

**Pull request merged**
