### PR TITLE
add TSZ and ADT-FSE algorithm

### PR DESCRIPTION
**Pull request by lx1zhong**

### CODE REVIEW

**Comment by sangshuduo** [comment]
[ 52%] Linking CXX executable ../../../../build/bin/pageBufferTest

[ 52%] Building C object community/source/common/CMakeFiles/common.dir/src/ttszip.c.o

[ 52%] Building C object community/source/common/CMakeFiles/common.dir/src/ttypes.c.o

[ 52%] Building C object community/source/common/CMakeFiles/common.dir/src/tvariant.c.o

[ 52%] Building C object community/source/common/CMakeFiles/common.dir/__/__/__/enterprise/src/plugins/common/src/tglobal.c.o

[ 52%] Built target cfgTest

[ 52%] Building CXX object community/source/libs/tdb/test/CMakeFiles/tdbTest.dir/tdbTest.cpp.o

[ 52%] Built target bloomFilterTest

[ 52%] Building CXX object community/source/libs/tdb/test/CMakeFiles/tdbPageRecycleTest.dir/tdbPageRecycleTest.cpp.o

/usr/bin/ld: ../../../../build/lib/libutil.a(tcompression.c.o): in function `tsCompressInit':

/home/TDinternal/community/source/util/src/tcompression.c:76: undefined reference to `tsLossyColumns'

/usr/bin/ld: /home/TDinternal/community/source/util/src/tcompression.c:82: undefined reference to `tsLossyColumns'

/usr/bin/ld: /home/TDinternal/community/source/util/src/tcompression.c:83: undefined reference to `tsLossyColumns'

/usr/bin/ld: /home/TDinternal/community/source/util/src/tcompression.c:87: undefined reference to `tsIfAdtFse'

/usr/bin/ld: /home/TDinternal/community/source/util/src/tcompression.c:87: undefined reference to `tsCurRange'

/usr/bin/ld: /home/TDinternal/community/source/util/src/tcompression.c:87: undefined reference to `tsMaxRange'

/usr/bin/ld: /home/TDinternal/community/source/util/src/tcompression.c:87: undefined reference to `tsDPrecision'

/usr/bin/ld: /home/TDinternal/community/source/util/src/tcompression.c:87: undefined reference to `tsFPrecision'

/usr/bin/ld: /home/TDinternal/community/source/util/src/tcompression.c:87: undefined reference to `tsCompressor'

[ 52%] Linking CXX executable ../../../../build/bin/taosbsearchTest

collect2: error: ld returned 1 exit status

make[2]: *** [community/source/util/test/CMakeFiles/pageBufferTest.dir/build.make:108: build/bin/pageBufferTest] Error 1

make[1]: *** [CMakeFiles/Makefile2:4396: community/source/util/test/CMakeFiles/pageBufferTest.dir/all] Error 2

make[1]: *** Waiting for unfinished jobs....

[ 52%] Linking CXX executable ../../../../../build/bin/tdbExOVFLTest

[ 53%] Linking CXX executable ../../../../../build/bin/tdbPageDefragmentTest

[ 53%] Built target taosbsearchTest

[ 53%] Built target tdbExOVFLTest

[ 53%] Linking CXX executable ../../../../../build/bin/tdbUtilTest

[ 53%] Built target tdbPageDefragmentTest

[ 53%] Built target tdbUtilTest

[ 53%] Linking CXX executable ../../../../../build/bin/tdbPageRecycleTest

[ 53%] Linking CXX static library ../../../build/lib/libcommon.a

[ 53%] Built target common

[ 53%] Linking CXX executable ../../../../../build/bin/tdbTest

[ 53%] Built target tdbPageRecycleTest

[ 53%] Built target tdbTest

make: *** [Makefile:166: all] Error 2

Command exited with non-zero status 1

0.13user 0.16system 2:11.99elapsed 0%CPU (0avgtext+0avgdata 49712maxresident)k

0inputs+368outputs (0major+5975minor)pagefaults 0swaps

script returned exit code 1

**Review by sangshuduo — CHANGES_REQUESTED** [review]
Please fix the compile failure.

**Comment by lx1zhong** [comment]
That's strange! 
It works on my machine, and I tried it on a newly installed ubuntu22.04 virtual machine, which also works.
As for this error,  variables such as 'tsLossyColumns' are declared in **tglobal.h** and defined in **tglobal.c**. And **tglobal.h** is included in **tcompression.c**. 
Sorry I don't see where the problem is. Maybe I need some help.

**Comment by lx1zhong** [comment]
I noticed an extra space at the end of this line
`#include "tglobal.h" `
Will this  this lead to the error?

**Review by hjxilinx — APPROVED** [review]

**Pull request merged**
