### PR TITLE
doc: update 10.cluster docs.md

### LINKED ISSUE #7628: In order to improve accuracy, could someone unify the word in the following place in the article?
To be precise, this word should be unified with other places
image

### PR DESCRIPTION
**Pull request by citizen233**
Fix #7628

### CODE REVIEW

**Review by jiajingbin — COMMENTED** [review]
No problem

**Comment by Aries-Lee1991** [comment]
We will make a certificate for the new contributor and give a souvenir. Can you leave your contact information or add me wechat (Aries_Lee1991) @citizen233

**Comment by citizen233** [comment]
@Aries-Lee1991 WeChat prompt: the user does not exist

**Comment by Aries-Lee1991** [comment]
> @Aries-Lee1991 WeChat prompt: the user does not exist

sorry, please add wechat 690754649

**Pull request merged**
