### PR TITLE
[TD-10896]<fix>: use taosa insteadof blm3

### PR DESCRIPTION
**Pull request by sangshuduo**
make taos adapter build/install works on mac too

### CODE REVIEW

**Comment by zitsen** [comment]
The command binary file name and config file name should be taosa/taosa.toml imo. @sangshuduo @huskar-t

**Comment by huskar-t** [comment]
> The command binary file name and config file name should be taosa/taosa.toml imo. @sangshuduo @huskar-t

I also think taosadapter is too long

**Review by huskar-t — APPROVED** [review]
LGTM

**Review by guanshengliang — APPROVED** [review]

**Comment by guanshengliang** [comment]
no problem with the submodule and the installation script

**Review by zitsen — APPROVED** [review]
LGTM

**Pull request merged**
