### PR TITLE
Update docs.md

### PR DESCRIPTION
**Pull request by dingbo8128**
delete Matlab and R

### CODE REVIEW

**Review by sangshuduo — APPROVED** [review]

**Review by tangfangzhi — APPROVED** [review]

**Review by huolibo — APPROVED** [review]
LGTM

**Review by jiacy-jcy — APPROVED** [review]

**Review by tomchon — APPROVED** [review]
lgtm

**Review by changxiaoqiang — COMMENTED** [review]
是不是也请将英文文档里面的链接修改了

**Review by changxiaoqiang — APPROVED** [review]
Approve

**Pull request merged**
