### PR TITLE
With log in macro

### PR DESCRIPTION
**Pull request by freemine**
add TLOG/TLOGLONG macro, so that compiler can check va-args for us.

and as such, fix lots of pitfalls happens in taosPrintLog call sites!

### CODE REVIEW

**Comment by localvar** [comment]
hi @freemine , your idea is great.

however, the implementation could be improved, below is a comparation of the binary sizes with/without your change:

```shell
zbm@aaa:~/project/td/community/debug/build/bin$ ll t*
-rwxrwxr-x 1 zbm zbm 3436392 Jun 11 14:25 taos*
-rwxrwxr-x 1 zbm zbm 4671488 Jun 11 14:25 taosd*
-rwxrwxr-x 1 zbm zbm 3422872 Jun 11 14:25 taosdemo*
-rwxrwxr-x 1 zbm zbm 3375480 Jun 11 14:25 taosdump*
-rwxrwxr-x 1 zbm zbm 3488240 Jun 11 14:25 tsim*
zbm@iZ2zed870nkxae0ylij2khZ:~/project/td/community/debug/build/bin$ ll t*
-rwxrwxr-x 1 zbm zbm 3008456 Jun 11 14:28 taos*
-rwxrwxr-x 1 zbm zbm 3856880 Jun 11 14:28 taosd*
-rwxrwxr-x 1 zbm zbm 2999456 Jun 11 14:28 taosdemo*
-rwxrwxr-x 1 zbm zbm 2952064 Jun 11 14:28 taosdump*
-rwxrwxr-x 1 zbm zbm 3064824 Jun 11 14:28 tsim*
```

you may notice all binaries increase at least 400k bytes while `taosd` increases 800k because of macro expansion.

**Comment by localvar** [comment]
hi @freemine , your idea is great.

however, the implementation could be improved, below is a comparation of the binary sizes with/without your change:

```shell
zbm@aaa:~/project/td/community/debug/build/bin$ ll t*
-rwxrwxr-x 1 zbm zbm 3436392 Jun 11 14:25 taos*
-rwxrwxr-x 1 zbm zbm 4671488 Jun 11 14:25 taosd*
-rwxrwxr-x 1 zbm zbm 3422872 Jun 11 14:25 taosdemo*
-rwxrwxr-x 1 zbm zbm 3375480 Jun 11 14:25 taosdump*
-rwxrwxr-x 1 zbm zbm 3488240 Jun 11 14:25 tsim*
zbm@aaa:~/project/td/community/debug/build/bin$ ll t*
-rwxrwxr-x 1 zbm zbm 3008456 Jun 11 14:28 taos*
-rwxrwxr-x 1 zbm zbm 3856880 Jun 11 14:28 taosd*
-rwxrwxr-x 1 zbm zbm 2999456 Jun 11 14:28 taosdemo*
-rwxrwxr-x 1 zbm zbm 2952064 Jun 11 14:28 taosdump*
-rwxrwxr-x 1 zbm zbm 3064824 Jun 11 14:28 tsim*
```

you may notice all binaries increase at least 400k bytes while `taosd` increases 800k because of macro expansion.

**Comment by freemine** [comment]
we can add a build flag to switch to va_args list

**Comment by freemine** [comment]
i guess buffer[....] are the major contribution to the size increase of the target.

thread local storage might be another solution to your concerns.

**Comment by localvar** [comment]
no, buffer in stack is just one instruction like below (x64 as example), no matter how big it is.
```asm
add rsp, bufsize
```
 and if there are other local variables, compiler even merge all of them into one instruction.

I notice the buffer is declared as:
```c
char           buffer[TLOG_MAX_LOGLINE_BUFFER_SIZE] = { 0 }; 
```

the `= {0}` result in something like:
```c
memset(buffer, 0, sizeof(buffer));
```

which contribute several bytes in each call as part of the macro expansion.

**Comment by freemine** [comment]
sorry, my fault. :)

**Comment by localvar** [comment]
@freemine , pls check https://stackoverflow.com/questions/11621043/how-should-i-properly-use-attribute-format-printf-x-y-inside-a-class, it might be a help.

**Comment by freemine** [comment]
@localvar thx. it's elegant in gcc, cause it's gcc's local dialect.

**Comment by localvar** [comment]
FYI, we've implement format check by `__attribute__((format))` and fix more than 100 related issues.
Thanks for your idea.

**Pull request closed without merging**
