### PR TITLE
Run unit test 'osTest' in test-all 

### PR DESCRIPTION
**Pull request by junli1026**
This PR modified the unit test of test-all script, changing from running 'queryTest' only to running an array of [queryTest, osTest].

### CODE REVIEW

**Comment by sangshuduo** [comment]
Is it necessary to run the unit test in test-all? Most unit test programs are the developer use to check the functionality of the early development phase on purpose.

**Review by sangshuduo — COMMENTED** [review]
Is it necessary to run the unit test in test-all? Most unit test programs are the developer use to check the functionality of the early development phase on purpose.

**Comment by junli1026** [comment]
> Is it necessary to run the unit test in test-all? Most unit test programs are the developer use to check the functionality of the early development phase on purpose.

OK, but queryTest is already there in test-all. 
I think it is very project dependent about how to use unit-test. Some projects use them as part of regression test, some  use it as part of the build process. 

It is your call to decide how to use unit test,  I just think it may benifit the code quality.

It is fine if you think

**Comment by sangshuduo** [comment]
OK. Let me close it. 

Put unit test in test-all or not is case by case. 

Thanks for your enthused contribution. :)

**Pull request closed without merging**
