### PR TITLE
test: scripts for all connector's sample codes

### PR DESCRIPTION
**Pull request by dingbo8128**

### CODE REVIEW

**Comment by gccgdb1234** [comment]
No changes in tests/parallel_test/cases.task? This is where the cases should be added.
I am fine with the newly added docs, samples and run scripts.

**Review by sangshuduo — APPROVED** [review]
LGTM

**Comment by sangshuduo** [comment]
didn't follow conventional commit format :)

**Comment by dingbo8128** [comment]
> No changes in tests/parallel_test/cases.task? This is where the cases should be added. I am fine with the newly added docs, samples and run scripts.

CI environment is not ready yet.  I will create another PR when CI cotainer is ready.

**Comment by dingbo8128** [comment]
> didn't follow conventional commit format :)

pleased to know where. could you please point out ?

**Comment by sangshuduo** [comment]
> > didn't follow conventional commit format :)
> 
> pleased to know where. could you please point out ?

subject need to be <catalog>[module]: description

**Pull request merged**
