### PR TITLE
[TD-11129]<test>: finish taosadapter perftest scripts

### PR DESCRIPTION
**Pull request by jiajingbin**
No need ci, main program is taosadapter_perftest.py which call other jmeter scripts.

### CODE REVIEW

**Review by xiaopingcs — APPROVED** [review]
Looks good

**Review by wu-champion — APPROVED** [review]
IP, port and similar parameters, it would be better if they can be turned into configuration options

**Comment by jiajingbin** [comment]
> IP, port and similar parameters, it would be better if they can be turned into configuration options

I will optimize these in the next version, including deployment automation, monitoring automation, etc.

**Review by plum-lihui — APPROVED** [review]
LGMT

**Pull request merged**
