### PR TITLE
[TD-3048]<feature>: support lines/stream/query_a/stop_query/ and so on.

### PR DESCRIPTION
**Pull request by zitsen**
commit 0edc106a76a95b28e65019c2ee4e4ed84530ad35
Author: Huo Linhe <linhehuo@gmail.com>
Date:   Thu Jul 29 21:13:13 2021 +0800

    doc: improve document for python connector

commit 84915de0831b49c8378a16242dd0dbba8aaf386f
Author: Huo Linhe <linhehuo@gmail.com>
Date:   Thu Jul 29 20:35:45 2021 +0800

    chore: add time elapsed

commit 1e8822e01bda96388a359363776792e261260b88
Author: Huo Linhe <linhehuo@gmail.com>
Date:   Thu Jul 29 20:26:01 2021 +0800

    feat: support multi bind

commit 82d823f6194471fd3324b50f7dfba0ee9f10a7dd
Author: Huo Linhe <linhehuo@gmail.com>
Date:   Thu Jul 29 16:42:05 2021 +0800

    feat: python support for async query and subscribe with callback

commit 8b9d36de2945906821225189cb47958e153d81e2
Author: Huo Linhe <linhehuo@gmail.com>
Date:   Wed Jul 28 18:09:09 2021 +0800

    feat: finish stream and stmt interface

commit bc871aa43e9fc28dd1b3f8784a8ac6ee988564b5
Author: Huo Linhe <linhehuo@gmail.com>
Date:   Mon Jul 26 20:21:27 2021 +0800

    feat: basic full-fetured implementations

commit e5f7a5213e9016c377a57485e8d5c12139ce0957
Author: Huo Linhe <linhehuo@gmail.com>
Date:   Fri Jul 23 10:33:14 2021 +0800

    tmp: refactor

### CODE REVIEW

**Comment by stevel032** [comment]
Quick feedback... I thought Python 2.x is not supported any more, but the pyproject.toml file says we still support it, can we clarify for sure?

**Comment by stevel032** [comment]
Another quick feedback... the code looks quite good overall, so far anyway, but I noticed some misspellings (such as "protocal"), perhaps we can run the code through a spell checker?

**Comment by stevel032** [comment]
Another question, why do we need two sets of functions sometimes? such:

```
def insertLines(self, lines):
 
  ... ...
 
def insert_lines(self, lines):
```

**Comment by zitsen** [comment]
> Quick feedback... I thought Python 2.x is not supported any more, but the pyproject.toml file says we still support it, can we clarify for sure?

Python 2.x is supported, as in official documents, but not 100% compatible, all async API will not work, but standard use cases works well.



> Another quick feedback... the code looks quite good overall, so far anyway, but I noticed some misspellings (such as "protocal"), perhaps we can run the code through a spell checker?

Fixed.



> Another question, why do we need two sets of functions sometimes? such:
> 
> ```
> def insertLines(self, lines):
>  
>   ... ...
>  
> def insert_lines(self, lines):
> ```

`insertLines` is added by Shenglian Zhou. I've already give a talk with him and confirmed to remove insertLines method(test case fixed).

**Comment by stevel032** [comment]
Hey @sangshuduo ,  I took a rough look at the code, and really cannot give any additional constructive feedback, except that the changes (in terms of line added/deleted) are pretty big. I don't think I'm the right person to review and approve. Perhaps you need to spend a bit more time?

**Comment by stevel032** [comment]
Another quick feedback, I noticed that we added "pandas" a new dependency, but did we mention somewhere in our documentation to install it first. Or better yet, is there documentation on preparation steps before the users can use our Python module?

**Comment by zitsen** [comment]
> Another quick feedback, I noticed that we added "pandas" a new dependency, but did we mention somewhere in our documentation to install it first. Or better yet, is there documentation on preparation steps before the users can use our Python module?

Pandas is not the dependency of python connector, but the dependency of the test cases (TDengine/tests/pytest/).

**Comment by sangshuduo** [comment]
> Hey @sangshuduo , I took a rough look at the code, and really cannot give any additional constructive feedback, except that the changes (in terms of line added/deleted) are pretty big. I don't think I'm the right person to review and approve. Perhaps you need to spend a bit more time?

yes. I also have commented that patch bulk size sugggestion to Linhe. 
I am reviewing this PR too. But really need lots of time to read them. I will give my comments later.

**Review by sangshuduo — COMMENTED** [review]
Will we support both poetry and pip? why we don't support python3.6 anymore?

**Comment by zitsen** [comment]
> Will we support both poetry and pip? why we don't support python3.6 anymore?

poetry and pip both are supported. Python3.6/2.7 are supported as runtime, Python3.7+ is required for develop and test (see pyproject.toml dev-dependencies)

**Review by sangshuduo — APPROVED** [review]
LGTM

**Pull request merged**
