### PR TITLE
Solve the problem of picture typesetting in English and Chinese documents.

### PR DESCRIPTION
**Pull request by daaaaaaaaaaa**
good first issue：https://github.com/taosdata/TDengine/issues/7844

### CODE REVIEW

**Review by jiacy-jcy — APPROVED** [review]

**Review by jiacy-jcy — COMMENTED** [review]
The url of the image should be 'page: // ' but not 'https: //'，such cases are not mistakes .
The pictures in the Chinese document are correct, you need to modify the English document according to the Chinese document.

**Comment by daaaaaaaaaaa** [comment]
> The url of the image should be 'page: // ' but not 'https: //'，such cases are not mistakes .
> The pictures in the Chinese document are correct, you need to modify the English document according to the Chinese document.

But it seems that the pictures of Chinese documents cannot be displayed?
图片不能显示

**Review by Aries-Lee1991 — COMMENTED** [review]
@Eliacy

**Review by Aries-Lee1991 — COMMENTED** [review]
@Eliacy

**Comment by Eliacy** [comment]
LGTM

**Pull request merged**
