### PR TITLE
[TD-11776]<fix>change taosdemo to taosBenchmark

### PR DESCRIPTION
**Pull request by zhaoyanggh**

### CODE REVIEW

**Review by sangshuduo — APPROVED** [review]
LGTM. Do we need merge taos-tools PR first then update commit in TDengine?

**Comment by zhaoyanggh** [comment]
> LGTM. Do we need merge taos-tools PR first then update commit in TDengine?

Yes, I think so. waiting for haoran's test result

**Comment by sangshuduo** [comment]
> > LGTM. Do we need merge taos-tools PR first then update commit in TDengine?
> 
> Yes, I think so. waiting for haoran's test result

OK

**Review by zyyang-taosdata — APPROVED** [review]
LGTM

**Review by tomchon — APPROVED** [review]

**Review by wenzhouwww — APPROVED** [review]

**Pull request merged**
