### PR TITLE
feat:  see #4016 

### PR DESCRIPTION
**Pull request by songtianyi**
- remove outdated rust binding
- add latest binding repo link as a submodule

### CODE REVIEW

**Review by sangshuduo — CHANGES_REQUESTED** [review]
failed to run on Ubuntu 20.04 with the develop branch. Could you please verify it again? Thanks.
======
 cargo run --example demo
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/examples/demo`
Can't create Tdengine: Invalid database name

**Comment by songtianyi** [comment]
> # failed to run on Ubuntu 20.04 with the develop branch. Could you please verify it again? Thanks.
> cargo run --example demo
> Finished dev [unoptimized + debuginfo] target(s) in 0.03s
> Running `target/debug/examples/demo`
> Can't create Tdengine: Invalid database name

Sorry. 
```
 fn main() {
-    let tde =
-        Tdengine::new("127.0.0.1:6030", "root", "taosdata", "top1", 0).unwrap_or_else(|err| {
-            eprintln!("Can't create Tdengine: {}", err);
-            process::exit(1)
-        });
+    let tde = Tdengine::new("127.0.0.1:6030", "root", "taosdata", "log", 0).unwrap_or_else(|err| {
+        eprintln!("Can't create Tdengine: {}", err);
+        process::exit(1)
+    });
```
Fixed. Change login db from custom  to taos default db 'log'

**Review by sangshuduo — CHANGES_REQUESTED** [review]
The latest commit of this PR is still 6 days ago. You need to update PR with the latest commit which already includes the fix. Thanks.

**Comment by songtianyi** [comment]
> The latest commit of this PR is still 6 days ago. You need to update PR with the latest commit which already includes the fix. Thanks.

The commits for fixing  `Can't create Tdengine: Invalid database name` was committed to another repo which linked to tdengine by git submodule and we talked about this in #4019

**Comment by songtianyi** [comment]
> The latest commit of this PR is still 6 days ago. You need to update PR with the latest commit which already includes the fix. Thanks.

They were committed to https://github.com/songtianyi/tdengine-rust-bindings

**Comment by sangshuduo** [comment]
@songtianyi you need update the submodule commit id too. otherwise, user will get an old commit with "git submodule update --init"

**Comment by songtianyi** [comment]
> @songtianyi you need update the submodule commit id too. otherwise, user will get an old commit with "git submodule update --init"

Done.

**Review by sangshuduo — APPROVED** [review]
Thanks.

**Pull request merged**
