### PR TITLE
1. odbc requirement check in CMakeLists.txt(s)

### PR DESCRIPTION
**Pull request by freemine**
check odbc requirements and configuration automatically
no necessary to specifiy cflags/link-options manually

### CODE REVIEW

**Comment by sangshuduo** [comment]
Please withhold googletest link.

**Review by sangshuduo — CHANGES_REQUESTED** [review]
please withhold googletest link

**Review by arielyang — APPROVED** [review]
It works fine on my MacBook Pro M1.

**Review by sangshuduo — APPROVED** [review]
LGTM

**Pull request merged**
