### PR TITLE
Add support for async insert and connection pool. 

### PR DESCRIPTION
**Pull request by robotspace**
Async query is wrapped now and only insert result is parsed. Connection pool is implemented.  Async query and connection pool give possibility to meet multiple requests in OpenResty. Watermark in current pool implementation is a good way to monitor the pressure on connection pool.
Add a test case for Lua connector in smoke test case list.

### CODE REVIEW

**Comment by sangshuduo** [comment]
@robotspace do you mind adding a test case to the test cases list for the smoke test to avoid new patch break the lua connector? The document how to add test case is here: https://github.com/taosdata/TDengine/blob/develop/tests/How-To-Run-Test-And-How-To-Add-New-Test-Case.md.

**Comment by robotspace** [comment]
@sangshuduo OK.

**Review by sangshuduo — CHANGES_REQUESTED** [review]
$ python3 ./test.py -f connector/lua.py
2021-05-31 23:17:49.470037 binPath /home/shuduo/work/taosdata/TDengine.orig/tests/pytest/util/../../../debug/
2021-05-31 23:17:49.470279 binPath real path /home/shuduo/work/taosdata/TDengine.orig/debug
2021-05-31 23:17:49.470440 stop all dnodes

2021-05-31 23:17:50.224953 psim is deployed and configured by /home/shuduo/work/taosdata/TDengine.orig/sim/psim/cfg/taos.cfg
2021-05-31 23:17:50.578714 dnode:1 is deployed and configured by /home/shuduo/work/taosdata/TDengine.orig/sim/dnode1/cfg/taos.cfg
2021-05-31 23:17:50.718524 taosd found in /home/shuduo/work/taosdata/TDengine.orig/debug

2021-05-31 23:17:50.720065 dnode:1 is running with nohup /home/shuduo/work/taosdata/TDengine.orig/debug/build/bin/taosd -c /home/shuduo/work/taosdata/TDengine.orig/sim/dnode1/cfg > /dev/null 2>&1 &
2021-05-31 23:17:51.275714 the dnode:1 has been started.
2021-05-31 23:17:51.276469 Procedures for tdengine deployed in 127.0.0.1

2021-05-31 23:17:51.276698 Procedures for testing self-deployment

2021-05-31 23:17:51.319371 start to execute /home/shuduo/work/taosdata/TDengine.orig/tests/pytest/connector/lua.py
2021-05-31 23:17:51.327154 prepare database:db

2021-05-31 23:17:51.422083 taosd found in /home/shuduo/work/taosdata/TDengine.orig/debug

2021-05-31 23:17:51.422135 /home/shuduo/work/taosdata/TDengine.orig/debug/../tests/examples/lua

lua_connector.c:5:10: fatal error: lua.h: No such file or directory
    5 | #include <lua.h>
      |          ^~~~~~~
compilation terminated.
sh: 1: lua: not found
2021-05-31 23:17:51.524595 /home/shuduo/work/taosdata/TDengine.orig/tests/pytest/connector/lua.py successfully executed


it can succeed even not executed. :)

**Comment by sangshuduo** [comment]
How about this way  #6321 to install the necessary library? @robotspace

**Comment by robotspace** [comment]
> How about this way  #6321 to install the necessary library? @robotspace

Sorry to leave a pitfall in the last commit. I will have a try to find another way. It may be a better way to return error if the environment can't meet the requirement because linux distributions have different package management tool. It's a hard work to install necessary libraries  automatically.

**Comment by robotspace** [comment]
Yes,  I agree that now. Since lua connector is not an default component yet, it is not a good idea to block smoke test or install the dependency manually. The  dependency is lua5.3 and it is a common choice now. Only lua5.1 exists in Openresty.  The dependency is as following: 
**lua_header_installed=`apt-cache policy liblua5.3-dev|grep Installed|grep none > /dev/null; echo $?`**

**Comment by robotspace** [comment]
> How about this way  #6321 to install the necessary library? @robotspace

Yes,  I agree that now. Since lua connector is not an default component yet, it is not a good idea to block smoke test or install the dependency manually. The  dependency is lua5.3 and it is a common choice now. Only lua5.1 exists in Openresty.  The command may look like **lua_header_installed=`apt-cache policy liblua5.3-dev|grep Installed|grep none > /dev/null; echo $?`**  @sangshuduo

**Comment by sangshuduo** [comment]
Okay, we can pick up 5.3 as you suggest.

should we remove the folder tests/examples/lua/lua51?

**Comment by robotspace** [comment]
> Okay, we can pick up 5.3 as you suggest.
> 
> should we remove the folder tests/examples/lua/lua51?

No. Please keep lua51 directory. It is version for OpenResty and dependency headers are included in that directory.

**Comment by sangshuduo** [comment]
OK

**Pull request merged**
