### PR TITLE
Update query api for Lua connector.

### PR DESCRIPTION
**Pull request by robotspace**
Update query api for Lua connector.
Add entrance for Lua connector introduction.

### CODE REVIEW

**Review by guanshengliang — APPROVED** [review]

**Comment by sangshuduo** [comment]
@robotspace hi, thanks for your contribution to add lua connector for TDengine. Could you please introduce how we can verify/test this lua connector works as expected or not? Then we would add the test case to make sure the connector works well in the future even something changed in TDengine.

**Comment by robotspace** [comment]
> @robotspace hi, thanks for your contribution to add lua connector for TDengine. Could you please introduce how we can verify/test this lua connector works as expected or not? Then we would add the test case to make sure the connector works well in the future even something changed in TDengine.

Thanks very much for your concern. The connector is implemented by Lua version5.3, so you may need to install Lua to execute the build.sh script and run test.lua. I have designed some cases such as creating table and inserting record, etc. I don't think this is the best way to verify connector. The key question is how to define pass/fail and get test result from tdengine's auto-test kit. It's quite a problem for me right now. I will try my best to find a solution to resolve it and send a blog to TAOS.

**Comment by sangshuduo** [comment]
@robotspace good to know your blog is coming. My email is sdsang@taosdata.com. Thanks.

**Comment by robotspace** [comment]
> @robotspace good to know your blog is coming. My email is [sdsang@taosdata.com](mailto:sdsang@taosdata.com). Thanks.

Got it.

**Pull request merged**
