### PR TITLE
Submission of HiveMQ TDengine extension

### PR DESCRIPTION
**Pull request by micli**
https://www.github.com/micli/Catfish

### CODE REVIEW

**Comment by sangshuduo** [comment]
感谢提交PR，我们会在挑战赛截止日后进行评选

**Comment by sangshuduo** [comment]
@micli 能否提供一个简要的文档说明？最好有英文版本。谢谢！

**Comment by micli** [comment]
Hi @sangshuduo:

Sorry for late reply, due to I muted all of notification from Github.
You could see design document at :https://github.com/micli/Catfish/blob/main/docs/design.md 
For Chinese version: https://github.com/micli/Catfish/blob/main/docs/design_cn.md

**Review by sangshuduo — CHANGES_REQUESTED** [review]
参赛作品需要以 TDengine 的 submodule 方式提交源代码目录到 src/connector 里

**Comment by micli** [comment]
Close due to reviewer asked put source code and distribution to src/connector.
Will submit another one.

**Pull request closed without merging**
