### PR TITLE
[TS-706]<test>count(tbname) disabled test coverage

### PR DESCRIPTION
**Pull request by liuyq-617**

### CODE REVIEW

**Review by xiaopingcs — APPROVED** [review]
looks good

**Review by wenzhouwww — COMMENTED** [review]
Looks good , UDF not support mix up with build_in funcion

**Comment by liuyq-617** [comment]
> Looks good , UDF not support mix up with build_in funcion

however,UDF mixed up with count(tbname)  does not cause the database to report an error

**Review by wenzhouwww — APPROVED** [review]

**Review by plum-lihui — APPROVED** [review]
LGTM

**Pull request merged**
