### PR TITLE
Update the dependencies required for runing testcase

### PR DESCRIPTION
**Pull request by tomchon**

### CODE REVIEW

**Review by sangshuduo — APPROVED** [review]
LGTM

**Comment by tomchon** [comment]
We need python3.8 or higher version to run test cases.Would we  mention it here? @sangshuduo

**Review by sangshuduo — CHANGES_REQUESTED** [review]
we should explicitly require using python3.

**Comment by sangshuduo** [comment]
> We need python3.8 or higher version to run test cases.Would we mention it here? @sangshuduo
 Yes.

**Comment by liuyq-617** [comment]
uiautomation is needed on windows

**Review by plum-lihui — APPROVED** [review]
lgtm

**Pull request merged**
