### PR TITLE
[TD-11700]<fix> Deal with the probabilistic failure of unique/dnode/alternativeRole.sim

### PR DESCRIPTION
**Pull request by guanshengliang**

### CODE REVIEW

**Review by plum-lihui — COMMENTED** [review]
The dnode1 should be dnode2 in line 45
The dnode1 should be dnode2 in line 46

**Review by xiaopingcs — APPROVED** [review]
looks good

**Comment by guanshengliang** [comment]
> The dnode1 should be dnode2 in line 45
> The dnode1 should be dnode3 in line 46

done

**Review by plum-lihui — APPROVED** [review]
lgtm

**Pull request merged**
