### PR TITLE
Feature/m2d

### PR DESCRIPTION
**Pull request by guanshengliang**

### CODE REVIEW

**Comment by zitsen** [comment]
@Eliacy request review for python connector documents

**Comment by Eliacy** [comment]
Document part is OK for me.

**Comment by zitsen** [comment]
@guanshengliang test_crash_gen_s3 is waiting for slave3 for a really long time.

**Comment by guanshengliang** [comment]
> @guanshengliang test_crash_gen_s3 is waiting for slave3 for a really long time.

running for https://github.com/taosdata/TDengine/pull/6132

**Pull request merged**
