### PR TITLE
[TD-4944]:c# connector nanosecond support

### PR DESCRIPTION
**Pull request by xleili**
C# connector nanosecond support 
1 /src/connector/C#/TDengineDiver.cs
2./test/example/C#/C#checker/C#checker.cs
3./test/example/C#/C#checker/TDengineDriver.cs
4./test/example/C#/TDengineDriver.cs
5./test/example/C#/taosdemo/TDengineDriver.cs

### CODE REVIEW

**Review by sangshuduo — CHANGES_REQUESTED** [review]
please fix indent.

**Review by xleili — COMMENTED** [review]
indent fix

**Review by xleili — COMMENTED** [review]
indent fix 2nd

**Review by sangshuduo — APPROVED** [review]
LGTM

**Review by zitsen — APPROVED** [review]
LGTM

**Pull request merged**
