### PR TITLE
add hivemq-tdengine-extension

### PR DESCRIPTION
**Pull request by huskar-t**
add hivemq-tdengine-extension to /src/connector/hivemq-tdengine-extension by git submodule. from repo [https://github.com/huskar-t/hivemq-tdengine-extension](https://github.com/huskar-t/hivemq-tdengine-extension)

### CODE REVIEW

**Review by guanshengliang — APPROVED** [review]

**Comment by sangshuduo** [comment]
@huskar-t 感谢提交PR，我们会在挑战赛截止日后进行评选

**Comment by guanshengliang** [comment]
This issue also requires a more detailed review by @sangshuduo

**Comment by huskar-t** [comment]
按照之前聊的构想，初步做了一个自定义json消息的版本[https://github.com/huskar-t/hivemq-tdengine-jdsl-extension](https://github.com/huskar-t/hivemq-tdengine-jdsl-extension)

**Comment by sangshuduo** [comment]
@huskar-t 能否提供一个简要的文档说明？最好有英文版本。谢谢！

**Comment by huskar-t** [comment]
@sangshuduo 在项目内有readme [https://github.com/huskar-t/hivemq-tdengine-jdsl-extension/blob/master/README.md](https://github.com/huskar-t/hivemq-tdengine-jdsl-extension/blob/master/README.md)

**Comment by huskar-t** [comment]
基础版的README [https://github.com/huskar-t/hivemq-tdengine-extension/blob/master/README.md](https://github.com/huskar-t/hivemq-tdengine-extension/blob/master/README.md)

**Review by sangshuduo — CHANGES_REQUESTED** [review]
$ git submodule update --init --recursive 
Cloning into '/home/shuduo/work/taosdata/TDengine.orig/src/connector/hivemq-tdengine-jdsl-extension'...
Warning: Permanently added the RSA host key for IP address '192.30.255.113' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:huskar-t/hivemq-tdengine-jdsl-extension.git' into submodule path '/home/shuduo/work/taosdata/TDengine.orig/src/connector/hivemq-tdengine-jdsl-extension' failed
Failed to clone 'src/connector/hivemq-tdengine-jdsl-extension'. Retry scheduled
Cloning into '/home/shuduo/work/taosdata/TDengine.orig/src/connector/hivemq-tdengine-jdsl-extension'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:huskar-t/hivemq-tdengine-jdsl-extension.git' into submodule path '/home/shuduo/work/taosdata/TDengine.orig/src/connector/hivemq-tdengine-jdsl-extension' failed
Failed to clone 'src/connector/hivemq-tdengine-jdsl-extension' a second time, aborting

能否改为 https 方式？

**Comment by huskar-t** [comment]
@sangshuduo 已更改

**Comment by huskar-t** [comment]
添加了英文文档

**Comment by jtao1735** [comment]
> @sangshuduo 基础版的README https://github.com/huskar-t/hivemq-tdengine-extension/blob/master/README.md

能否还提供一英文版？

**Comment by huskar-t** [comment]
@jtao1735 英文文档 [https://github.com/huskar-t/hivemq-tdengine-extension/blob/master/README_EN.md](https://github.com/huskar-t/hivemq-tdengine-extension/blob/master/README_EN.md)

**Comment by huskar-t** [comment]
remove submodule jdsl

**Review by sangshuduo — APPROVED** [review]

**Pull request merged**
