### PR TITLE
[TD-10872]<feature>taosdemo support unicode chinese

### PR DESCRIPTION
**Pull request by zhaoyanggh**

### CODE REVIEW

**Review by sangshuduo — COMMENTED** [review]
is there a command-line option is equal to the JSON argument?

**Review by afwerar — APPROVED** [review]
LGTM

**Comment by zhaoyanggh** [comment]
> is there a command-line option is equal to the JSON argument?

I add -C option for cmdline

**Review by sangshuduo — APPROVED** [review]
LGTM

**Pull request merged**
