### PR TITLE
Feature/query

### PR DESCRIPTION
**Pull request by hjxilinx**

### CODE REVIEW

**Review by guanshengliang — APPROVED** [review]

**Comment by hjxilinx** [comment]
PR info:
1.	The binary tags can be used as the join query condition for super tables.
2.	Fix some bugs in fill query for super table.
3.	Fix the crash while executing “show variables” command
4.	The constant value column in select clause is supported
5.	Reducing the memory consumptions during the time interval query
6.	Fix JDBC memory leak whiling invoking the C native library.
7.	Optimized the last_row query performance.
8.	The default output column name for arithmetic expression is used the original user input expression.
9.	Add some checks for memory allocation failure.

**Comment by hjxilinx** [comment]
PR info:
1.	The binary tags can be used as the join query condition for super tables.
2.	Fix some bugs in fill query for super table.
3.	Fix the crash while executing “show variables” command
4.	The constant value column in select clause is supported
5.	Reducing the memory consumptions during the time interval query
6.	Fix JDBC memory leak whiling invoking the C native library.
7.	Optimized the last_row query performance.
8.	The default output column name for arithmetic expression is used the original user input expression.
9.	Add some checks for memory allocation failure.

**Comment by hjxilinx** [comment]
PR info:
1.	The binary tags can be used as the join query condition for super tables.
2.	Fix some bugs in fill query for super table.
3.	Fix the crash while executing “show variables” command
4.	The constant value column in select clause is supported
5.	Reducing the memory consumptions during the time interval query
6.	Fix JDBC memory leak whiling invoking the C native library.
7.	Optimized the last_row query performance.
8.	The default output column name for arithmetic expression is used the original user input expression.
9.	Add some checks for memory allocation failure.

**Comment by hjxilinx** [comment]
PR info:
1.	The binary tags can be used as the join query condition for super tables.
2.	Fix some bugs in fill query for super table.
3.	Fix the crash while executing “show variables” command
4.	The constant value column in select clause is supported
5.	Reducing the memory consumptions during the time interval query
6.	Fix JDBC memory leak whiling invoking the C native library.
7.	Optimized the last_row query performance.
8.	The default output column name for arithmetic expression is used the original user input expression.
9.	Add some checks for memory allocation failure.

**Comment by hjxilinx** [comment]
PR info:
1.	The binary tags can be used as the join query condition for super tables.
2.	Fix some bugs in fill query for super table.
3.	Fix the crash while executing “show variables” command
4.	The constant value column in select clause is supported
5.	Reducing the memory consumptions during the time interval query
6.	Fix JDBC memory leak whiling invoking the C native library.
7.	Optimized the last_row query performance.
8.	The default output column name for arithmetic expression is used the original user input expression.
9.	Add some checks for memory allocation failure.

**Pull request merged**
