### PR TITLE
docs(driver): add macOS installation instructors for node

### PR DESCRIPTION
**Pull request by xleili**

### CODE REVIEW

**Comment by sangshuduo** [comment]
@xleili  any plan for english version?

**Review by sangshuduo — CHANGES_REQUESTED** [review]
any plan for english version?

**Comment by xleili** [comment]
> any plan for english version?
added

**Comment by sangshuduo** [comment]
https://english.stackexchange.com/questions/112257/above-or-later-when-referencing-a-range-of-versions-of-software

**Review by sangshuduo — APPROVED** [review]
LGTM

**Pull request merged**
