### PR TITLE
Add CODE_OF_CONDUCT-CN.md

### PR DESCRIPTION
**Pull request by EchoHou2000**
This is a Chinese version of CODE_OF_CONDUCT.md.

### CODE REVIEW

**Comment by LookSin** [comment]
I have just signed CLA.

**Review by arielyang — CHANGES_REQUESTED** [review]
1. Please split this PR into 2 pieces.
2. The bug report PR is not necessary enough.
3. Is there any FORMAL Chinese version of CODE_OF_CONDUCT file template?

**Comment by LookSin** [comment]
1.Ok, I will  split this PR into 2 pieces as soon as possible.
2.You are right. I now think the bug report PR is  really not necessary enough.
3.Sorry, I haven't this file template yet.

**Comment by LookSin** [comment]
Sorry, I did something wrong. I will close this PR and start from scratch.

**Pull request closed without merging**
