### PR TITLE
add hivemq tdengine extension 

### PR DESCRIPTION
**Pull request by sdvdxl**
- [x] Support TDengine jdbc
- [x] Support TDengine http
- [x] Support the encoding of the payload stored in the configuration (original string, base64 string, HEX string, can be extended)
- [x] Support custom database name and table name, and automatically create database and table
- [x] Support extension hot load and stop
- [x] Support asynchronous storage, does not affect the original mqtt message processing
- [x] Support custom queue size and thread size
- [x] Support super table, table name strategy (client_id, username)

extension url： https://github.com/sdvdxl/hivemq-tdengine-extension

## 中文说明

- [x] 支持使用jdbc方式将 mqtt 消息写入 TDengine
- [x] 支持使用http RESTful 方式将 mqtt 消息写入 TDengine
- [x] 支持配置存储的payload的编码（原始字符串、base64字符串、HEX 字符串，可以扩展）
- [x] 支持自定义数据库名字和表名字，并且自动创建库和表
- [x] 支持hivemq热加载、停止
- [x] 支持同时启用http和jdbc方式写入不同的表并且配置不同编码或者其中之一
- [x] 支持异步入库
- [x] 支持自定义入库队列大小，线程大小
- [x] 支持超级表，表名策略（client_id、username

插件地址： https://github.com/sdvdxl/hivemq-tdengine-extension

### CODE REVIEW

**Comment by sangshuduo** [comment]
感谢提交PR，我们会在挑战赛截止日后进行评选

**Comment by sangshuduo** [comment]
@sdvdxl 能否提供一个英文版本的简要说明文档？谢谢！

**Comment by sdvdxl** [comment]
> @sdvdxl 能否提供一个英文版本的简要说明文档？谢谢！

@sangshuduo 已在项目readme中增加，默认是英文，中文移动到了 https://github.com/sdvdxl/hivemq-tdengine-extension/blob/master/README_zh.md。

**Comment by sangshuduo** [comment]
$ git fetch origin pull/3749/head:hivemq-3749

$ git checkout hivemq-3749  

$ git submodule update --init --recursive  

fatal: remote error: upload-pack: not our ref 0d394b922c2ebe758d29e936d9a9120b89ffa4bd

fatal: The remote end hung up unexpectedly

Fetched in submodule path 'src/connector/hivemq-tdengine-extension', but it did not contain 0d394b922c2ebe758d29e936d9a9120b89ffa4bd. Direct fetching of that commit failed.

$ git diff HEAD^

diff --git a/src/connector/hivemq-tdengine-extension b/src/connector/hivemq-tdengine-extension

index 683723525..72447bf9a 160000

\--- a/src/connector/hivemq-tdengine-extension

+++ b/src/connector/hivemq-tdengine-extension

@@ -1 +1 @@

\-Subproject commit 683723525177a4db5bd85a1c18ff6a4039505a41

+Subproject commit 72447bf9a0b11ae781405c4e1a2e1ef674e13a6b-dirty

不能拉下来代码

**Review by sangshuduo — COMMENTED** [review]
无法拉下代码

**Comment by sdvdxl** [comment]
我本地试了下没问题
image


我merge了一下最新的TDengine库的代码，并且重新操作了一下，也没遇到这个问题
image

你再试试？ 如果还有问题可以直接克隆这个库也是可以的  https://github.com/sdvdxl/hivemq-tdengine-extension

**Comment by sangshuduo** [comment]
$ git submodule update --init --recursive  

Submodule 'src/connector/go' (https://github.com/taosdata/driver-go) registered for path 'src/connector/go'

Submodule 'src/connector/grafanaplugin' (https://github.com/taosdata/grafanaplugin) registered for path 'src/connector/grafanaplugin'

Submodule 'src/connector/hivemq-tdengine-extension' (git@github.com:sdvdxl/hivemq-tdengine-extension.git) registered for path 'src/connector/hivemq-tdengine-extension'

Cloning into '/home/shuduo/work/taosdata/tdengine-hivemq/src/connector/go'...

Cloning into '/home/shuduo/work/taosdata/tdengine-hivemq/src/connector/grafanaplugin'...

Cloning into '/home/shuduo/work/taosdata/tdengine-hivemq/src/connector/hivemq-tdengine-extension'...

git@github.com: Permission denied (publickey).

fatal: Could not read from remote repository.

Please make sure you have the correct access rights

and the repository exists.

fatal: clone of 'git@github.com:sdvdxl/hivemq-tdengine-extension.git' into submodule path '/home/shuduo/work/taosdata/tdengine-hivemq/src/connector/hivemq-tdengine-extension' failed

Failed to clone 'src/connector/hivemq-tdengine-extension'. Retry scheduled

Cloning into '/home/shuduo/work/taosdata/tdengine-hivemq/src/connector/hivemq-tdengine-extension'...

git@github.com: Permission denied (publickey).

fatal: Could not read from remote repository.

Please make sure you have the correct access rights

and the repository exists.

fatal: clone of 'git@github.com:sdvdxl/hivemq-tdengine-extension.git' into submodule path '/home/shuduo/work/taosdata/tdengine-hivemq/src/connector/hivemq-tdengine-extension' failed

Failed to clone 'src/connector/hivemq-tdengine-extension' a second time, aborting

全新 clone 的 TDengine 也不行，可以试试把 git@github.com 改成 https

**Comment by sangshuduo** [comment]
我手动改成 https 后可以了

**Review by sangshuduo — COMMENTED** [review]
Sorry, we will close this PR as the competition finished.

**Pull request closed without merging**
