### PR TITLE
[TD-12163] <test> add case for TD-12163 to resolve no response after alter table schema by using restful interfacase

### PR DESCRIPTION
**Pull request by wu-champion**

### CODE REVIEW

**Review by huskar-t — APPROVED** [review]
LGTM

**Review by xiaopingcs — CHANGES_REQUESTED** [review]
Please fix conflicts

**Review by xiaopingcs — APPROVED** [review]

**Comment by xiaopingcs** [comment]
Looks good

**Review by jiajingbin — APPROVED** [review]
LGTM

**Pull request closed without merging**
