### PR TITLE
early allocation of epoll notification fd

### PR DESCRIPTION
**Pull request by freemine**
early allocate epoll fd to minimize the probability of runtime failure during tcp connection shutdown

### CODE REVIEW

**Comment by freemine** [comment]
I refetched repo again, and found there's no conflict.
i also noticed PR #2172. I can wait until #2172 is merged then.

**Comment by guanshengliang** [comment]
@jtao1735  just modified this file
now there is some conflict
please check and initiate a new PR, then let @jtao1735  review

**Comment by freemine** [comment]
thx.

the latest code for cleanup in case of early init failure may suffer intialized mutex un-destroyed (if numThreads are modified) or destroying an uninitialized mutex(if otherwise). but making code simple and clear is a good suggestion. i'll make some modification upon this.

as for kqueue/epoll, i searched the code and found src/plugins/http/src/httpServer.c is also relying on epoll. are we considering to port that code too?

**Comment by freemine** [comment]
as for kqueue/epoll issue:
seems like currently, tdengine is servicing one connection per thread. thus, kqueue/epoll does not bring any benefit.

if it's decided to switch to multiplex mode, why not relay on libevent/libev/libuv?

**Comment by jtao1735** [comment]
> as for kqueue/epoll issue:
> seems like currently, tdengine is servicing one connection per thread. thus, kqueue/epoll does not bring any benefit.
> 
> if it's decided to switch to multiplex mode, why not relay on libevent/libev/libuv?

We planned to implement kqueue at the beginning of the project, but never got free time to implement it. Also, we planed to adopt DPDK for more efficient solution, you can do some research on it.

**Pull request closed without merging**
