### PR TITLE
[TD-6380] fix some broken links in documention20 folder

### LINKED ISSUE #6380: many images and links not work in documentation20 folder
目录：documention20
问题：文档中的许多图片和链接不生效，无法正确加载图片和跳转链接。

比如：
image

### PR DESCRIPTION
**Pull request by jiaoqiyuan**
Fixes #6380

### CODE REVIEW

**Comment by jiaoqiyuan** [comment]
En folder has the same problem, I will fix it later.

**Comment by jiaoqiyuan** [comment]
Done, could review.

**Review by Eliacy — CHANGES_REQUESTED** [review]
Hi friend, thanks for the attentive work. However, I can't approve this merging. In fact, we use a PHP program named Grav to render these Markdown files. According to the standard of Grav, all links to images should be start with page://, and all relative links should be wrote according  to the final url in Web browsers.

I'm sorry the Markdown files will have broken links in local view, but our official web site will always sync all the content. Please check these docs in https://www.taosdata.com/cn/documentation 

Thanks for engagement~~

**Comment by jiaoqiyuan** [comment]
Ok, I will close this PR.

**Pull request closed without merging**
