### PR TITLE
Add a build option to disable embedded lua lib. By default enable

### PR DESCRIPTION
**Pull request by robotspace**
Since diverge from develop branch a long way, porting modifications to current branch to avoid merge conflict.

### CODE REVIEW

**Comment by sangshuduo** [comment]
Windows build failed as followiwng:

...
LINK : warning LNK4075: 蹇界暐鈥�/INCREMENTAL鈥�(鐢变簬鈥�/LTCG鈥濊鑼�)
  姝ｅ湪鍒涘缓搴� ..\..\..\..\build\bin\taos.lib 鍜屽璞� ..\..\..\..\build\bin\taos.exp
query.lib(qScript.c.obj) : error LNK2001: 鏃犳硶瑙ｆ瀽鐨勫閮ㄧ鍙� lua_pushcclosure
query.lib(qScript.c.obj) : error LNK2001: 鏃犳硶瑙ｆ瀽鐨勫閮ㄧ鍙� luaopen_table
query.lib(qScript.c.obj) : error LNK2001: 鏃犳硶瑙ｆ瀽鐨勫閮ㄧ鍙� luaL_loadstring
query.lib(qScript.c.obj) : error LNK2001: 鏃犳硶瑙ｆ瀽鐨勫閮ㄧ鍙� lua_pushlstring
query.lib(qScript.c.obj) : error LNK2001: 鏃犳硶瑙ｆ瀽鐨勫閮ㄧ鍙� lua_type
query.lib(qScript.c.obj) : error LNK2001: 鏃犳硶瑙ｆ瀽鐨勫閮ㄧ鍙� luaopen_base
query.lib(qScript.c.obj) : error LNK2001: 鏃犳硶瑙ｆ瀽鐨勫閮ㄧ鍙� lua_setfield
query.lib(qScript.c.obj) : error LNK2001: 鏃犳硶瑙ｆ瀽鐨勫閮ㄧ鍙� lua_next
query.lib(qScript.c.obj) : error LNK2001: 鏃犳硶瑙ｆ瀽鐨勫閮ㄧ鍙� luaL_newstate
query.lib(qScript.c.obj) : error LNK2001: 鏃犳硶瑙ｆ瀽鐨勫閮ㄧ鍙� lua_createtable
query.lib(qScript.c.obj) : error LNK2001: 鏃犳硶瑙ｆ瀽鐨勫閮ㄧ鍙� lua_tonumber
query.lib(qScript.c.obj) : error LNK2001: 鏃犳硶瑙ｆ瀽鐨勫閮ㄧ鍙� lua_tolstring
query.lib(qScript.c.obj) : error LNK2001: 鏃犳硶瑙ｆ瀽鐨勫閮ㄧ鍙� luaopen_string
query.lib(qScript.c.obj) : error LNK2001: 鏃犳硶瑙ｆ瀽鐨勫閮ㄧ鍙� lua_call
query.lib(qScript.c.obj) : error LNK2001: 鏃犳硶瑙ｆ瀽鐨勫閮ㄧ鍙� lua_pushstring
query.lib(qScript.c.obj) : error LNK2001: 鏃犳硶瑙ｆ瀽鐨勫閮ㄧ鍙� luaopen_math
query.lib(qScript.c.obj) : error LNK2001: 鏃犳硶瑙ｆ瀽鐨勫閮ㄧ鍙� luaL_checknumber
query.lib(qScript.c.obj) : error LNK2001: 鏃犳硶瑙ｆ瀽鐨勫閮ㄧ鍙� lua_pushnumber
query.lib(qScript.c.obj) : error LNK2001: 鏃犳硶瑙ｆ瀽鐨勫閮ㄧ鍙� lua_close
query.lib(qScript.c.obj) : error LNK2001: 鏃犳硶瑙ｆ瀽鐨勫閮ㄧ鍙� lua_getfield
query.lib(qScript.c.obj) : error LNK2001: 鏃犳硶瑙ｆ瀽鐨勫閮ㄧ鍙� lua_pcall
query.lib(qScript.c.obj) : error LNK2001: 鏃犳硶瑙ｆ瀽鐨勫閮ㄧ鍙� lua_rawseti
query.lib(qScript.c.obj) : error LNK2001: 鏃犳硶瑙ｆ瀽鐨勫閮ㄧ鍙� lua_settop
query.lib(qScript.c.obj) : error LNK2001: 鏃犳硶瑙ｆ瀽鐨勫閮ㄧ鍙� luaopen_debug
query.lib(qScript.c.obj) : error LNK2001: 鏃犳硶瑙ｆ瀽鐨勫閮ㄧ鍙� luaL_loadbuffer
query.lib(qScript.c.obj) : error LNK2001: 鏃犳硶瑙ｆ瀽鐨勫閮ㄧ鍙� lua_pushnil
..\..\..\..\build\bin\taos.exe : fatal error LNK1120: 26 涓棤娉曡В鏋愮殑澶栭儴鍛戒护
NMAKE : fatal error U1077: “"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe"”: 返回代码“0xffffffff”
Stop.
NMAKE : fatal error U1077: “"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\nmake.exe"”: 返回代码“0x2”
Stop.
...

**Review by sangshuduo — APPROVED** [review]
LGTM

**Review by guanshengliang — APPROVED** [review]

**Comment by guanshengliang** [comment]
LGTM

**Review by yihaoDeng — APPROVED** [review]
LGTM

**Pull request merged**
