### PR TITLE
[TD-11255]<fix>taosdemo cmdLine -l

### PR DESCRIPTION
**Pull request by zhaoyanggh**
:

### CODE REVIEW

**Review by afwerar — APPROVED** [review]
LGTM

**Comment by sangshuduo** [comment]
tools/taosdemoAllTest/TD-10539/create_taosdemo.py failed

**Comment by zhaoyanggh** [comment]
> tools/taosdemoAllTest/TD-10539/create_taosdemo.py failed

Modified test case, -l option will only add columns instead of change default columns and -b settings

**Review by sangshuduo — APPROVED** [review]
LGTM

**Pull request merged**
