### PR TITLE
[TD-11129]<test>: Finish taosadapter performance scripts

### PR DESCRIPTION
**Pull request by jiajingbin**
Auto deploy:

single taosd node;

taosd cluster

taosadapter_separate_deploy

Audo monitor:

auto deploy node_exporter

auto deploy process_exporter

auto deploy prometheus

auto deploy grafana(but you need to import dashboard by manual)

Testcases:

Telnet-http

Json-http

Telnet-tcp

### CODE REVIEW

**Comment by jiajingbin** [comment]
"TDengine/tests/perftest-scripts/taosadapter_perftest/old" can be ignored

**Comment by liuyq-617** [comment]
if jmeter not found,test can't stop

**Comment by liuyq-617** [comment]
after deploying jmeter, it reports:/bin/sh: jmeter: command not found
however,it runs well next time

**Comment by liuyq-617** [comment]
have an option: revert all your behaviors?

**Review by plum-lihui — APPROVED** [review]
lgtm

**Pull request merged**
