### PR TITLE
[TD-10739]<test>: add test case for interp

### PR DESCRIPTION
**Pull request by wenzhouwww**
add test case for interp for TD-10736

### CODE REVIEW

**Comment by happyguoxy** [comment]
Agree to add this special scenario

**Review by happyguoxy — APPROVED** [review]
Agree to add this special scenario

**Review by plum-lihui — APPROVED** [review]
lgtm

**Comment by jiacy-jcy** [comment]
I think it is OK.

**Comment by jiacy-jcy** [comment]
lgtm

**Pull request merged**
